### ISSUE TITLE
nomad-ingress: Missed colon in traefik config

### ISSUE THREAD

**Issue by STommydx** [narwhl/blueprint#23]
https://github.com/narwhl/blueprint/blob/0b615f6ea81b56744e1e3902b4aa4b443a447063/modules/nomad-ingress/templates/traefik.nomad.hcl.tftpl#L55-L59

fix: 

```toml
[entryPoints]
  [entryPoints.http]
    address = ":{{ env `NOMAD_PORT_http` }}"
  [entryPoints.https]
    address = ":{{ env `NOMAD_PORT_https` }}"
```
